export const sidebarData = [
    { id: 1, userName: 'User 1' , profileImg : ''},
    { id: 2, userName: 'User 2' , profileImg : ''},
    { id: 3, userName: 'User 3' , profileImg : ''},
    { id: 4, userName: 'User 4' , profileImg : ''},
    { id: 5, userName: 'User 5' , profileImg : ''},
    { id: 6, userName: 'User 6' , profileImg : ''},
    { id: 7, userName: 'User 7' , profileImg : ''},
    { id: 8, userName: 'User 8' , profileImg : ''},
    { id: 9, userName: 'User 9' , profileImg : ''},
    { id: 10, userName: 'User 10' , profileImg : ''},
    { id: 11, userName: 'User 11' , profileImg : ''},
    { id: 12, userName: 'User 12' , profileImg : ''},
    { id: 13, userName: 'User 13' , profileImg : ''},
    { id: 14, userName: 'User 14' , profileImg : ''},
    { id: 15, userName: 'User 15' , profileImg : ''},
    { id: 16, userName: 'User 16' , profileImg : ''},
    { id: 17, userName: 'User 17' , profileImg : ''},
    { id: 18, userName: 'User 18' , profileImg : ''},
    { id: 19, userName: 'User 19' , profileImg : ''},
    { id: 20, userName: 'User 20' , profileImg : ''},
    { id: 21, userName: 'User 21' , profileImg : ''},
    { id: 22, userName: 'User 22' , profileImg : ''},

]